# Generated by Django 3.1.2 on 2020-11-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201118_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
