# Generated by Django 3.1.2 on 2020-11-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20201118_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
